

#切换环境
spring:
  profiles:
    active: dev
# JavaMailSender 邮件发送的配置
  mail:
      host: smtp.qq.com
      username: 949812478@qq.com
      password: oljqzbqhlqprbeai
      protocol: smtp
      properties.mail.smtp.auth: true
      properties.mail.smtp.port: 465
      properties.mail.display.sendmail: Javen
      properties.mail.display.sendname: Spring Boot Guide Email
      properties.mail.smtp.starttls.enable: true
      properties.mail.smtp.starttls.required: true
      properties.mail.smtp.ssl.enable: true
      default-encoding: utf-8


